// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrate needs a direct (non-pooled) connection — Prisma's advisory locks
  // don't work reliably through PgBouncer's transaction pooler. The app's
  // runtime client (lib/prisma.ts) uses the pooled DATABASE_URL instead.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
