-- Add nullable first: cuid() is generated by Prisma Client, not SQL, so
-- existing rows need a backfilled value before the column can be NOT NULL.
ALTER TABLE "parties" ADD COLUMN "organizerToken" TEXT;

-- Backfill each existing party with its own unique random token.
UPDATE "parties" SET "organizerToken" = replace(gen_random_uuid()::text, '-', '') WHERE "organizerToken" IS NULL;

ALTER TABLE "parties" ALTER COLUMN "organizerToken" SET NOT NULL;
CREATE UNIQUE INDEX "parties_organizerToken_key" ON "parties"("organizerToken");
